# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd
#   namespace: argocd
# spec:
#   project: default

#   source:
#     path: init
#     repoURL: https://github.com/matanmiz1/argocd-super.git
#     targetRevision: HEAD
#   destination:
#     server: {{ .Values.spec.destination.server }}
#     namespace: argocd
