apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: karpenter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: karpenter
    repoURL: https://github.com/matanmiz1/argocd-super.git
    targetRevision: HEAD
    helm:
      valuesObject:
        # nodeSelector:
        #   eks.amazonaws.com/nodegroup: # TODO: change terraform to have name to initial node group
        clusterName: "ie-test-eks"
        EC2NodeClass:
          role: "ie-test-eks-nodes-group"
        karpenter:
          settings:
            clusterName: "ie-test-eks"
            clusterEndpoint: "https://D5AE13E5BCA772D49D52DB736262C56D.gr7.eu-west-1.eks.amazonaws.com"
            interruptionQueue: "Karpenter-ie-test-eks"
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::883241448326:role/KarpenterControllerRole-ie-test-eks"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
