apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/matanmiz1/argocd-super.git
    targetRevision: HEAD
    path: helm/karpenter
    helm:
      valueFiles:
        - /live/global/env.yaml
        - /live/global/karpenter.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
