apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/matanmiz1/argocd-super.git
    targetRevision: HEAD
    path: helm/karpenter
    helm:
      valuesObject:
        # nodeSelector:
        #   eks.amazonaws.com/nodegroup: # TODO: change terraform to have name to initial node group
        clusterName: ie-test-eks
        EC2NodeClass:
          role: ie-test-eks-nodes-group
        karpenter:
          settings:
            clusterName: ie-test-eks
            clusterEndpoint: https://C4EEA19857BA15239F25FEC8EB147E5A.gr7.eu-west-1.eks.amazonaws.com
            interruptionQueue: Karpenter-ie-test-eks
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::883241448326:role/KarpenterControllerRole-ie-test-eks
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
