apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
spec:
  source:
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.10.0
    chart: aws-load-balancer-controller
    helm:
      valueFiles:
        - /projects/infra-master/aws-load-balancer-controller-helm-values.yaml
  destination:
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
