apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gp3
spec:
  sources:
    - repoURL: https://github.com/matanmiz1/argocd-super.git
      targetRevision: HEAD
      path: helm/storage-class
      helm:
        valueFiles:
          - $values/projects/infra-master/applications/gp3-helm-values.yaml
    - repoURL: https://github.com/matanmiz1/argocd-super.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
