apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

namePrefix: infra-master-

resources:
  - argocd-application.yaml
  - aws-load-balancer-controller-application.yaml
  - gp3-application.yaml
  # - karpenter-application.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    patch: |-
      - op: add
        path: /spec/project
        value: default
      - op: add
        path: /spec/destination/name
        value: in-cluster
