{{- range .Values.children }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/matanmiz1/argocd-super.git
    targetRevision: HEAD
    path: helm/infra-apps
    helm:
      valueFiles:
        - /live/global/env.yaml
  destination:
    server: {{ $endpoint }}
    namespace: argocd # namespace per cluster

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
{{- end }}
