{{- range $key, $values := .Values.clusters }}
  {{- $endpoint := $values.endpoint }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: super-apps--{{ $key }}
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/matanmiz1/argocd-super.git
    targetRevision: HEAD
    path: apps/inflate
  destination:
    server: {{ $endpoint }}
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
