apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Values.EC2NodeClass.name | quote }}
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        encrypted: true
        volumeSize: {{ .Values.EC2NodeClass.rootSize | quote }}
        volumeType: gp2 # TODO: gp3
  # metadataOptions:
  #   httpEndpoint: enabled
  #   httpProtocolIPv6: disabled
  #   httpPutResponseHopLimit: 2
  #   httpTokens: required
  role: {{ .Values.EC2NodeClass.role | required ".Values.EC2NodeClass.role is required." }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName | quote }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName | quote }}
  tags:
    Name: {{ .Values.clusterName }}-karpenter
    Type: karpenter_compute
  # userData: |-
  #   #!/bin/bash