{{- range $key, $value := .Values.nodePools }}
{{- if $value.enabled }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ $key | quote }}
spec:
  disruption: {{ $value.disruption | toYaml | nindent 4 }}
  limits:
    cpu: {{ $value.limits.cpu }}
    memory: {{ $value.limits.memory | quote }}
  template:
    metadata:
      labels:
        nodePool: {{ $key | quote }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: main
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - d
        - g
        - i
        - m
        - p
        - r
        - x
        - z
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
        {{- if $value.enableSpot }}
        - spot
        {{- end }}
      {{- if not $value.selectiveInstanceTypes }}
      - key: "node.kubernetes.io/instance-type"
        operator: NotIn
        values: {{ $value.selectiveInstanceTypes }}
      {{- end }}
      {{- if $value.expireAfter }}
      expireAfter: {{ $value.expireAfter }}
      {{- end }}
      startupTaints:
        - key: ebs.csi.aws.com/agent-not-ready
          effect: NoExecute
      {{- if $value.taintNodes }}
      taints:
      - key: nodePool
        value: {{ $key | quote }}
        effect: NoSchedule
      {{ end }}
{{- end }}
{{- end }}
