apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inflate
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/matanmiz1/argocd-super.git
    targetRevision: HEAD
    path: apps/inflate
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
