apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: super-master-app-of-apps
  namespace: argocd
spec:
  # project: default
  source:
    repoURL: https://github.com/matanmiz1/argocd-super.git
    path: projects/super-master/applications
    targetRevision: HEAD
  destination:
    # name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
